# Note: DaemonSet rolling update will become true in 1.6 (https://github.com/kubernetes/kubernetes/issues/22543), in the meantime you need to do a manual refresh
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd
    version: v1
    kubernetes.io/cluster-service: !!str true
  annotations:
    config-version: !!str 1
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd
        version: v1
        kubernetes.io/cluster-service: !!str true
      annotations:
        config-version: !!str 1
    spec:
      containers:
        - name: fluentd
          image: sportebois/fluentd-kubernetes-loggly-daemonset:loggly-psc
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "eval $(psc decrypt-env -r $PSC_REGION)  && sed -i \"s/LOGGLY_TOKEN/$(echo $LOGGLY_TOKEN | sed 's/-/\\-/g')/g\" /fluentd/etc/fluent.conf && exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT"]

          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
            - name: LOGGLY_TOKEN
              valueFrom:
                configMapKeyRef:
                    name: fluentd-loggly
                    key: logglyToken
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentconf
              mountPath: /fluentd/etc/
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluentconf
          configMap:
            name: fluentd-loggly
